import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const NeueMontrealRegular = localFont({
  src: "./fonts/NeueMontreal-Regular.otf",
  variable: "--font-neue-montreal",
  weight: "400",
});

const NeueMontrealBold = localFont({
  src: "./fonts/NeueMontreal-Bold.otf",
  variable: "--font-neue-montreal-bold",
  weight: "800",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${NeueMontrealRegular.variable} ${NeueMontrealBold.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
